Do not run nova services as root
openstack-k8s-operators/placement-operator pull request #107
Opened 2023-11-16 14:37 UTC by gibizer

Implements: https://issues.redhat.com/browse/OSPRH-1374

2023-11-16 14:46 UTC, gibizer commented
/test precommit-check
```
   * could not run steps: step precommit-check failed: test "precommit-check" failed: could not watch pod: the pod ci-op-gids8xyf/precommit-check failed after 2m3s (failed containers: test): ContainerFailed one or more containers exited \
```

2023-11-16 14:49 UTC, SeanMooney requested changes

2023-11-16 14:49 UTC, SeanMooney commented on api/bases/placement.openstack.org_placementapis.yaml
> -    controller-gen.kubebuilder.io/version: v0.11.1
this is proably not intentional

2023-11-16 14:52 UTC, gibizer commented on api/bases/placement.openstack.org_placementapis.yaml
> -    controller-gen.kubebuilder.io/version: v0.11.1
true. fixed.

2023-11-16 14:53 UTC, bogdando reviewed
lgtm

2023-11-20 13:06 UTC, gibizer commented
/hold

This should not work as kolla_set_config should fail.

Also we cannot simply switch to the placement user in the container as that user is not in the kolla group:
```
❯ oc rsh placement-7ccc6bc7f5-cfchj
Defaulted container "placement-api" out of: placement-api, init (init)
sh-5.1# id
uid=0(root) gid=0(root) groups=0(root)
sh-5.1# cat /etc/passwd | grep placement
placement:x:997:994:OpenStack Placement:/:/bin/bash
sh-5.1# cat /etc/group | grep kolla
kolla:x:42400:
sh-5.1# 
```

2023-11-20 13:09 UTC, gibizer commented
And we have a strange dbsync command:
```
	DBSyncCommand = "/usr/local/bin/kolla_set_configs && su -s /bin/sh -c \"placement-manage db sync\" placement"
```

2023-11-20 16:43 UTC, gibizer commented
We need a fix in the tcib image first https://github.com/openstack-k8s-operators/tcib/pull/102

2023-11-22 09:52 UTC, gibizer commented
tcib fix merged but there is still no container image built in https://quay.io/repository/podified-antelope-centos9/openstack-placement-api?tab=tags&tag=latest so we wait...

2023-11-23 09:08 UTC, gibizer commented
container promotion is blocked on https://issues.redhat.com/browse/OSPCIX-119

2023-12-05 16:28 UTC, SeanMooney approved these changes
https://issues.redhat.com/browse/OSPCIX-119 is closed 
and there was a successful promotion yesterday
https://review.rdoproject.org/zuul/build/97b34cff01744289b42f01944b777616
so i belive we can now proceed with this

@gibi if you agree then feel free to drop your hold

2023-12-07 15:15 UTC, gibizer commented
/unhold

2023-12-07 15:16 UTC, gibizer commented
This has the same limitation as nova-operator has. We cannot remove the usage of root from the container as kolla_set_config needs sudo.

2023-12-07 15:17 UTC, gibizer commented
/hold
We need to wait for https://github.com/openstack-k8s-operators/openstack-operator/pull/591 to pick up the new dataplane-operator that will pick up the new placement-api tcib image.

2023-12-07 15:22 UTC, gibizer commented
> /hold We need to wait for [openstack-k8s-operators/openstack-operator#591](https://github.com/openstack-k8s-operators/openstack-operator/pull/591) to pick up the new dataplane-operator that will pick up the new placement-api tcib image.

I mixed up this needs a new placement-operator to pick up a new placement-api tcib image. But we are in placement-operator so we don't have to wait for that.

2023-12-07 15:22 UTC, gibizer commented
/unhold

2023-12-08 13:33 UTC, bogdando commented
/LGTM

2023-12-08 13:34 UTC, bogdando approved these changes

2023-12-08 13:37 UTC, merged