Support attaching pods to networks using net-attach-defs and exposing api via metallb
openstack-k8s-operators/placement-operator pull request #113
Opened 2023-02-03 09:30 UTC by stuggi

* If needed, service pods can be attach to networks using the `networkAttachments` list in the CR. Its a list of pre-created net-attach-defs names. Per default the pods won't get attached.

```
spec:
...
      networkAttachments:
      - internalapi
```
Depends-On: https://github.com/openstack-k8s-operators/lib-common/pull/133

* introduce externalEndpoints Parameters to configure metallb service using the pre-created metallb IPAddressPool and L2Advertisement . 

E.g. to expose the api on an internalapi network which
* should be registered as the internal endpoint
* its metallb ipaddresspool is configured in an osp-internalapi object
*  and request a specific IP which is shared with other services

```
...
spec:
...
      externalEndpoints:
      - endpoint: internal
        ip: 172.17.0.202
        ipAddressPool: osp-internalapi
        sharedIP: true
```

* removes registration of admin endpoint

Depends-On: https://github.com/openstack-k8s-operators/lib-common/pull/160

2023-02-03 09:30 UTC, stuggi commented
/hold

2023-02-03 11:18 UTC, SeanMooney requested changes
my main feedback is i would like to see envtest coverage of this before we merge it.

overall the design looks ok. the MetalLBConfig probably could live in lib common to the infra operator instead of redefining it in all the operators. that is probably the thing i would cahge the most but in general the patch looks reasonable

2023-02-03 11:18 UTC, SeanMooney commented on api/v1beta1/placementapi_types.go
> +type MetalLBConfig struct {
this could live in lib common by the way

2023-02-03 11:18 UTC, SeanMooney commented on api/v1beta1/placementapi_types.go
> +	ExternalEndpoints []MetalLBConfig `json:"externalEndpoints"`
more vobose the VIP but sure that works too

2023-02-03 11:18 UTC, SeanMooney commented on api/v1beta1/placementapi_types.go
> +
by the way the placment CRD has yet to be broken into a public template and private spec

so when w edo that these will need to be included in the public PlacementAPITemplate

This does not affect this pr just more a note to self

2023-02-03 11:18 UTC, SeanMooney commented on config/crd/bases/placement.openstack.org_placementapis.yaml
> +                description: ExternalEndpoints, expose a VIP via MetalLB on the pre-created
by the way im not 100% sure we need to mention MetalLB here
technically this could be anything that implement the loadblancer type for a service right.

2023-02-03 11:18 UTC, SeanMooney commented on config/crd/bases/placement.openstack.org_placementapis.yaml
> +                      - public
ok so these map to the keystone endpoint type and we are intentionally not allowing this for the admin type.

2023-02-03 14:25 UTC, stuggi commented on api/v1beta1/placementapi_types.go
> +type MetalLBConfig struct {
I wanted to have it versioned and having defaults. therefore lib-common is probably not the best place. putting it in the infra-operator is probably a good idea. I'll follow up on this when we work on the other networking things adding to the infra-operator (ipam, dns, ...)

2023-02-06 11:02 UTC, gibizer commented on api/v1beta1/placementapi_types.go
> +
Please note that nova-operator also does not define NovaTemplate. The NovaSpec is used by the OpenStackControlPlane CR directly. For the nova-operator NovaSpec contains everything that is expected to be provided by the client. If openstack-operator wants to hide and therefore generate some of those inputs then openstack-operator needs to define the NovaTemplate with the restricted field set.

The nova-operator defines *Template structs for each nova internal CR and include the *Template in NovaSpec. Then the Nova controller uses the value from the template when generate the nova internal CR spec instances and fill in the fields of the spec that are not part of the template from its internal state. 

As placement has no internal CRs I dont see how templates are useful here.

2023-02-06 12:13 UTC, gibizer requested changes
I have couple of comments inline.

2023-02-06 12:13 UTC, gibizer commented on api/v1beta1/placementapi_types.go
> +	NetworkAttachments []string `json:"networkAttachments,omitempty"`
Am I correct that the Spec.NetworkAttachments defines what networks placement-api should be attached to and Status.NetworkAttachments signals when those attachment has been made by the reconciliation? Do we also want a Condition that signals that all requested network attachment has been made successfully?

2023-02-06 12:13 UTC, gibizer commented on config/crd/bases/placement.openstack.org_placementapis.yaml
> +    controller-gen.kubebuilder.io/version: v0.9.2
please use a fresh controler-gen as we moved to 0.10.0 in placement when we bumped to go 1.19. (You might need to delete the repo local ./bin directory to let the makefile redownlod the fresh version.)

2023-02-06 12:13 UTC, gibizer commented on controllers/placementapi_controller.go
Can we generate the network annotations once and only pass them to the DbSyncJob and Deployment

2023-02-06 12:13 UTC, gibizer commented on controllers/placementapi_controller.go
> +	instance.Status.NetworkAttachments = instance.Spec.NetworkAttachments
Do we have any way to mirror a condition from MetalLB or Deployment that shows that the requested network connection succeeded?

Can one attachment fail to apply while another succeeds? 

In general: how can we expose a status that helps troubleshooting such network setup failures?

2023-02-06 12:23 UTC, stuggi commented on api/v1beta1/placementapi_types.go
> +	// Networks list of NetworkAttachment to expose the services to
ack, will change the desc

2023-02-06 12:28 UTC, stuggi commented on api/v1beta1/placementapi_types.go
> +	// IPAddressPool if set, expose VIP via MetalLB on the address pool
why do you think we should have the IPAddressPool optional? I don't think we want MetalLB to allocate IPs from any configured pool with free addresses.

2023-02-06 12:29 UTC, stuggi commented on api/v1beta1/placementapi_types.go
> +	// IP, request given IP if available
right, if the pool is configured with `autoAssign: true`, which is the default, it will pick a free one. will update the desc to me more specific

2023-02-06 12:34 UTC, stuggi commented on api/v1beta1/placementapi_types.go
> +	NetworkAttachments []string `json:"networkAttachments,omitempty"`
right, it defines what networks the pods should be attached to. but it only adds the required annotation to the pod definition. if there is some typo in the NAD name, or the NAD is missing, there will be no error in scheduling. I think what we want is a check via a webhook if the NAD exists and if not blocks errors the update/create of the CR.

2023-02-06 12:34 UTC, stuggi commented on config/crd/bases/placement.openstack.org_placementapis.yaml
> +    controller-gen.kubebuilder.io/version: v0.9.2
ack

2023-02-06 12:35 UTC, stuggi commented on config/crd/bases/placement.openstack.org_placementapis.yaml
> +                description: ExternalEndpoints, expose a VIP via MetalLB on the pre-created
ack, I can remove the MetalLB reference here.

2023-02-06 12:38 UTC, stuggi commented on config/crd/bases/placement.openstack.org_placementapis.yaml
> +                      - public
the latest commit basically removes the creation of the admin endpoint. That's the topic I brought up in last weeks meeting and the only service which was not clear was keystone. After checking with dec dfg, it was deprecated in rocky and removed in train for keystone (https://bugs.launchpad.net/keystone/+bug/1829453).

2023-02-06 12:39 UTC, stuggi commented on controllers/placementapi_controller.go
yes could do that. will change it

2023-02-06 13:19 UTC, stuggi commented on controllers/placementapi_controller.go
> +	instance.Status.NetworkAttachments = instance.Spec.NetworkAttachments
For NAD -  Instead of just assigning the spec.NetworkAttachments to the status would be to check a pods `k8s.v1.cni.cncf.io/network-status` annotation for having an interface with IP in the list. We could instead add a map[string][]string to the status with the NAD name as the key and all pods IPs from there. If there are less IPs as replicas per network have a condition which reflect it.

For MetalLB - its just a service (LoadBalancer). there is no condition to sync. the only check we could do is to validate if the service is of type `LoadBalancer` that the `service.loadBalancer` has an ingress IP
~~~
status:
  loadBalancer:
    ingress:
    - ip: 172.17.0.210
~~~

and create a condition which reflects this

2023-02-06 14:20 UTC, gibizer commented on api/v1beta1/placementapi_types.go
> +	// IPAddressPool if set, expose VIP via MetalLB on the address pool
I think I misunderstood the doc here then. 
> IPAddressPool if set, expose

means to me that it is allowed to be unset as well. Anyhow if this field is mandatory then lets mark it with `// +kubebuilder:validation:Required`. I guess we can also say `// +kubebuilder:validation:MinLength=1` to forbid the empty string as an input here.

2023-02-06 14:20 UTC, gibizer commented on api/v1beta1/placementapi_types.go
> +	NetworkAttachments []string `json:"networkAttachments,omitempty"`
So such a typo would go unnoticed but the pods will be missing the assumed connectivity.
I agree that we need some validation here to prevent accepting an input that will not work. However I'm wondering if we need to support the following scenario:
* placement is created with a NAD that not exists yet
* NAD is created later
* => the placement-api pods eventually get connected to the requested network

If we need to support such async creation scenario then the validation webhook is too strict and we need to implement something similar to what we do when the Secret (osp-secret) is not exist yet when the PlacementAPI CR is created.

2023-02-06 14:20 UTC, gibizer commented on controllers/placementapi_controller.go
> +	instance.Status.NetworkAttachments = instance.Spec.NetworkAttachments
Thanks for explaining it. The `k8s.v1.cni.cncf.io/network-status` sounds like something we want to roll up into the status of the PlacementAPI CR. For me it would be enough to have a condition that is true iff all the requested NADs has a corresponding interface with IP in `k8s.v1.cni.cncf.io/network-status` . But if it is easier to have a `map[string][]string` field showing the actual IP mapping then that is also OK to me.

2023-02-07 13:12 UTC, SeanMooney commented on api/v1beta1/placementapi_types.go
> +
there are some filed that i am not sure whoudl be public 
specifically https://bugzilla.redhat.com/show_bug.cgi?id=2166968

i also am not sure that i agree the templates should be defined in the OpenStack operator

i really do think that the novaTemplate and placementTemplate should live in the service operator if they are required.

that is a separate conversation however so i don't want to hold up this PR for that.
I still have a Audit the public API of the Placement operator task in the back of my mind and expect use to remove or internalise some fields.
the databaseUser is perhaps the only one however that we need to fix curenlty.

2023-02-07 13:14 UTC, SeanMooney commented on api/v1beta1/placementapi_types.go
> +	// IPAddressPool if set, expose VIP via MetalLB on the address pool
im not sure it is.
i think you can have a default IP pool for metalLB but we might want to require it

2023-02-07 13:15 UTC, SeanMooney commented on api/v1beta1/placementapi_types.go
> +type MetalLBConfig struct {
notihg about libcommon means it cant be versioned.
lib-common will need to be versioned eventually.

but the infra-operator is likely a better long term fit.

2023-02-07 13:17 UTC, SeanMooney commented on api/v1beta1/placementapi_types.go
> +	NetworkAttachments []string `json:"networkAttachments,omitempty"`
i would prefer to avoid webhooks unless we need too.
my preference would be to check this is the reconsile loop and set the input ready condition to false if the attachments do not exist

we can also have a dedicated condition for the attachments if we wanted too but we would have to handle it specially in the case where there were no attachment like setting it to True automatically in that case.

2023-02-07 13:44 UTC, SeanMooney commented on config/crd/bases/placement.openstack.org_placementapis.yaml
> +                      - public
i don't think the removal of the admin endpoint was ever discussed with other projects.
for nova at least we still expect the admin endpoint to exist even if its not strictly required. so we should not assume that we will not require admin endpoint for other project.

2023-02-07 13:56 UTC, gibizer commented on config/crd/bases/placement.openstack.org_placementapis.yaml
> +                      - public
@SeanMooney do we have a special use of the admin endpoint in nova? I think public meant to be accessible from outside of the cloud, internal meant to be accessible within the cloud. But why we have admin?

2023-02-07 13:57 UTC, gibizer commented on api/v1beta1/placementapi_types.go
> +	// IPAddressPool if set, expose VIP via MetalLB on the address pool
anyhow my comment here is that this field either marked Optional or Required to make its usage clear.

2023-02-13 14:57 UTC, stuggi commented on config/crd/bases/placement.openstack.org_placementapis.yaml
> +                      - public
I brought it up in our Tuesday meeting 2 weeks ago and the only concern was if keystone still uses it. I clarified this. If you prefer, I can extract this into a separate PR for each operator and bring it up with each operator group.

2023-02-13 14:57 UTC, stuggi commented on api/v1beta1/placementapi_types.go
> +	// Networks list of NetworkAttachment to expose the services to
done

2023-02-13 14:58 UTC, stuggi commented on api/v1beta1/placementapi_types.go
> +	// IPAddressPool if set, expose VIP via MetalLB on the address pool
you can, but I don't think this is useful in our case and we want the user to be explicite on the pool to use. I have marked it as Required.

2023-02-13 14:58 UTC, stuggi commented on api/v1beta1/placementapi_types.go
> +	// IP, request given IP if available
done

2023-02-13 14:59 UTC, stuggi commented on config/crd/bases/placement.openstack.org_placementapis.yaml
> +    controller-gen.kubebuilder.io/version: v0.9.2
done

2023-02-13 14:59 UTC, stuggi commented on controllers/placementapi_controller.go
done

2023-02-13 15:01 UTC, stuggi commented on controllers/placementapi_controller.go
> +	instance.Status.NetworkAttachments = instance.Spec.NetworkAttachments
Added a condition, and the pod network information as a `map[string][]string`. roll up the full network-status has a lot more information, so for now reduced it to the ip info, e.g. for a deployment with 3 replicas

```
  networkAttachments:
    openshift-sdn:
    - 10.130.1.16
    - 10.128.2.44
    - 10.131.0.155
    openstack/internalapi:
    - 172.17.0.225
    - 172.17.0.227
    - 172.17.0.226
    openstack/storage:
    - 172.18.0.225
    - 172.18.0.227
    - 172.18.0.226
```

2023-02-13 15:05 UTC, stuggi commented on config/crd/bases/placement.openstack.org_placementapis.yaml
> +                description: ExternalEndpoints, expose a VIP via MetalLB on the pre-created
done

2023-02-13 15:25 UTC, gibizer commented on api/v1beta1/placementapi_types.go
> +	// IPAddressPool if set, expose VIP via MetalLB on the address pool
works for me.

2023-02-13 15:41 UTC, stuggi commented on api/v1beta1/placementapi_types.go
> +	NetworkAttachments []string `json:"networkAttachments,omitempty"`
fyi and completeness, it was not fully correct what I mentioned above. when there is a typo in the NAD, or an issue with the NAD config, the scheduling will not fail (as said above), but the pod creation fails like e.g.:

```
Events:                                                                                                                                                                                         
  Type     Reason                  Age   From               Message                                                                                                                   
  ----     ------                  ----  ----               -------                                 
  Normal   Scheduled               42s   default-scheduler  Successfully assigned openstack/keystone-f7979d754-5cx87 to ostest-worker-0 by ostest-master-2                                                          
  Normal   AddedInterface          40s   multus             Add eth0 [10.130.0.26/23] from openshift-sdn                                                                                                             
  Normal   AddedInterface          40s   multus             Add net1 [172.17.0.225/28] from openstack/internalapi                                                                                                    
  Warning  FailedCreatePodSandBox  39s   kubelet            Failed to create pod sandbox: rpc error: code = Unknown desc = failed to create pod network sandbox k8s_keystone-f7979d754-5cx87_openstack_3022bad8-8fa4-
4a16-b29b-9be065f587ef_0(fd988e239372e703775779e3284dba42e0101ce5e40e70c7a203a4746211b74f): error adding pod openstack_keystone-f7979d754-5cx87 to CNI network "multus-cni-network": plugin type="multus" name="multus-cni-network" failed (add): [openstack/keystone-f7979d754-5cx87/3022bad8-8fa4-4a16-b29b-9be065f587ef:storage]: error adding container to network "storage": IPAM plugin returned missing IP config   
```

As the operator is not the direct owner of the pod it won't get triggered from that event. The current check will cover the non existing NAD, but not when there is an issue with the config of the NAD as in this example.

2023-02-13 15:42 UTC, stuggi commented on controllers/placementapi_controller.go
> +	if len(instance.Spec.NetworkAttachments) == 0 || networkReady {
right, I added this later and missed to update the condition. will do, thanks!

2023-02-13 15:44 UTC, stuggi commented on controllers/placementapi_controller.go
> +	if len(instance.Spec.NetworkAttachments) == 0 || networkReady {
done

2023-02-13 15:59 UTC, stuggi commented on api/v1beta1/placementapi_types.go
> +	NetworkAttachments []string `json:"networkAttachments,omitempty"`
probably could watch the pods based on the service label we add.

2023-02-13 17:00 UTC, stuggi commented on api/v1beta1/placementapi_types.go
> +	NetworkAttachments []string `json:"networkAttachments,omitempty"`
well thats tricky, the information is not available from the pod object. its only available from the event list, but the failing event is not the last in the list of events, so its not easy to map e.g. an error es above to be the current state. I'll keep checking for possibility to checks this for later as a follow up.

2023-02-13 17:15 UTC, gibizer commented on api/v1beta1/placementapi_types.go
> +	NetworkAttachments []string `json:"networkAttachments,omitempty"`
I guess we need to handle this with documentation if there is no easy way to gather the information automatically.

2023-02-13 17:23 UTC, gibizer commented
I think my comments got fixed. I think we need some test coverage for this in envtest eventually. Unfortunately the placement envtest test coverage is not complete enough to simply add this in. First we need to add tests to cover creating the Deployment. Then we can assert if certain things are set on the Deployment properly. Nova can serve as an example though. @stuggi let me know if you need help with the envtest things.

2023-02-14 03:57 UTC, SeanMooney commented on api/v1beta1/placementapi_types.go
> +	NetworkAttachments []string `json:"networkAttachments,omitempty"`
does the NAD have a status field?
ideally we woudl validate that the NAD is correct by checking some Ready state on the NAD CR  and only proceed to create our statefule sets/pods if the NAD exits and is in a valid sate.

this is really not something endusers should have to debug by looking at pods.
they are not really part of our public API.

our use of pods/statefulest ectra are all internal implemation details.
if its not in a CRD that is provided by our operators, end users shouuld not need to look at it to debug failures like that ideally.

2023-02-14 07:18 UTC, stuggi commented on api/v1beta1/placementapi_types.go
> +	NetworkAttachments []string `json:"networkAttachments,omitempty"`
no, the NAD does not have a status, but I think we revisit if the user creates the NADs or likely that a controller creates them based on an network description we have for the IPAM. I'd suggest we revisit this when we work on that.

2023-02-15 17:17 UTC, stuggi commented
> I think my comments got fixed. I think we need some test coverage for this in envtest eventually. Unfortunately the placement envtest test coverage is not complete enough to simply add this in. First we need to add tests to cover creating the Deployment. Then we can assert if certain things are set on the Deployment properly. Nova can serve as an example though. @stuggi let me know if you need help with the envtest things.

lib-common PR merged and the open PRs in sync. So this is good for another, maybe final review. As discussed in our sync meeting yesterday, I'd like to get those network patches landed asap as there are a couple other tasks to be worked on to get this in into the march demo which I want to do next. I'd come back to the testing after the demo work.

2023-02-17 09:27 UTC, gibizer approved these changes
Looks good to me. We will need to go back to this to add EnvTest coverage.

2023-02-17 11:11 UTC, stuggi commented
/unhold

2023-02-17 11:14 UTC, gibizer approved these changes
still looks good

2023-02-17 11:17 UTC, merged