Add scale kuttl tests
openstack-k8s-operators/placement-operator pull request #154
Opened 2023-04-06 17:36 UTC by jamepark4

2023-04-06 17:40 UTC, jamepark4 commented on config/samples/placement_v1beta1_placementapi.yaml
> +namespace: openstack
Would it make more sense to create a config/samples/kuttl_placement_v1beta1_placementapi.yaml file and use that for deploying placement versus leveraging this file?

2023-04-10 16:11 UTC, EliadCohen commented on kuttl-test.yaml
> +#   make kuttl_keystone
Keystone? (nit)

2023-04-10 16:17 UTC, jamepark4 commented on kuttl-test.yaml
> +#   make kuttl_keystone
Thanks!

2023-04-11 17:18 UTC, gibizer reviewed
I tried to follow the instructions to run the test but I failed on the keystone prerequisites.

2023-04-11 17:18 UTC, gibizer commented on kuttl-test.yaml
> +
I tried to follow this instructions:
I did the following against a fresh crc:
// in install_yamls
make keystone_kuttl

But the target failed with:
```
 logger.go:42: 19:13:20 | change_keystone_config/4-change_keystone_config | starting test step 4-change_keystone_config
    logger.go:42: 19:13:20 | change_keystone_config/4-change_keystone_config | running command: [sh -c oc patch keystoneapi -n openstack keystone --type='json' -p='[{"op": "replace", "path": "/spec/customServiceConfig", "value": "[DEFAULT]\ndebug = false"}]'
        ]
    logger.go:42: 19:13:20 | change_keystone_config/4-change_keystone_config | keystoneapi.keystone.openstack.org/keystone patched
    logger.go:42: 19:13:23 | change_keystone_config/4-change_keystone_config | running command: [sh -c $KEYSTONE_KUTTL_DIR/../common/scripts/check_debug_in_keystone_pod_logs.sh --reverse]
    logger.go:42: 19:13:23 | change_keystone_config/4-change_keystone_config | /home/gibi/upstream/git/openstack-k8s-operators/install_yamls/out/operator/keystone-operator/tests/kuttl/tests/../common/scripts/check_debug_in_keystone_pod_logs.sh: 5: [: --reverse: unexpected operator
    logger.go:42: 19:13:24 | change_keystone_config/4-change_keystone_config | error: arguments in resource/name form may not have more than one slash
    logger.go:42: 19:13:25 | change_keystone_config/4-change_keystone_config | running command: [sh -c $KEYSTONE_KUTTL_DIR/../common/scripts/check_debug_in_keystone_pod_logs.sh --reverse]
    logger.go:42: 19:13:25 | change_keystone_config/4-change_keystone_config | /home/gibi/upstream/git/openstack-k8s-operators/install_yamls/out/operator/keystone-operator/tests/kuttl/tests/../common/scripts/check_debug_in_keystone_pod_logs.sh: 5: [: --reverse: unexpected operator
```

Did I missed something?

2023-04-11 18:02 UTC, jamepark4 commented on config/samples/placement_v1beta1_placementapi.yaml
> +namespace: openstack
Yea it does not need anything special at this time so I think I would prefer the option to patch the namespace with kustomize.

2023-04-11 19:35 UTC, jamepark4 commented on kuttl-test.yaml
> +
Can you retry with the updated steps whenever you have time?

2023-04-12 14:19 UTC, gibizer commented
/ok-to-test

2023-04-12 15:44 UTC, gibizer commented on kuttl-test.yaml
> +# 3. The above environment variables PLACEMENT_KUTTL_CONF and PLACEMENT_KUTTL_TEST_DIR are set
Is it PLACEMENT_KUTTL_TEST_DIR or PLACEMENT_KUTTL_DIR? I think the test code uses the latter.

2023-04-12 15:44 UTC, gibizer commented on kuttl-test.yaml
> +
Sorry I mixed up things yesterday with the keystone_kuttl target. 

Today I followed the new instructions (thanks for that!). 

```
gibi@bedrock:~/upstream/git/openstack-k8s-operators/install_yamls                                                                                                                       $ env | grep PLACEMENT
PLACEMENT_KUTTL_CONF=../placement-operator/kuttl-test.yaml
PLACEMENT_KUTTL_DIR=../placement-operator/test/kuttl/tests
$ kubectl-kuttl test --config ${PLACEMENT_KUTTL_CONF} ${PLACEMENT_KUTTL_DIR} 
[...snip...]
    logger.go:42: 17:07:29 | placement_scale/1-deploy_placement | PlacementAPI:openstack/placement created
    logger.go:42: 17:07:29 | placement_scale/1-deploy_placement | test step completed 1-deploy_placement
    logger.go:42: 17:07:29 | placement_scale/2-patch_placement_deploy | starting test step 2-patch_placement_deploy
    logger.go:42: 17:07:29 | placement_scale/2-patch_placement_deploy | running command: [sh -c oc patch placementapi -n openstack placement --type='json' -p='[{"op": "replace", "path": "/spec/secret", "value":"osp-secret"}]'
        oc patch placementapi -n openstack placement --type='json' -p='[{"op": "replace", "path": "/spec/storageClass", "value":"local-storage"}]'
        ]
    logger.go:42: 17:07:29 | placement_scale/2-patch_placement_deploy | placementapi.placement.openstack.org/placement patched
    logger.go:42: 17:07:29 | placement_scale/2-patch_placement_deploy | Warning: unknown field "spec.storageClass"
    logger.go:42: 17:07:29 | placement_scale/2-patch_placement_deploy | placementapi.placement.openstack.org/placement patched (no change)
    logger.go:42: 17:07:33 | placement_scale/2-patch_placement_deploy | running command: [sh -c source $PLACEMENT_KUTTL_DIR/../lib/helper_functions.sh
        apiEndpoints=$(oc get -n openstack PlacementAPI placement -o go-template-file=$PLACEMENT_KUTTL_DIR/../go_templates/apiEndpoints.gotemplate)
        assert_regex $apiEndpoints 'http:\/\/placement-internal\.openstack\.svc.*'
        assert_regex $apiEndpoints 'http:\/\/placement-public-openstack\.apps.*'
        ]
    logger.go:42: 17:07:33 | placement_scale/2-patch_placement_deploy | sh: 1: source: not found
    logger.go:42: 17:07:33 | placement_scale/2-patch_placement_deploy | sh: 3: assert_regex: not found
    logger.go:42: 17:07:33 | placement_scale/2-patch_placement_deploy | sh: 4: assert_regex: not found
    logger.go:42: 17:07:34 | placement_scale/2-patch_placement_deploy | running command: [sh -c source $PLACEMENT_KUTTL_DIR/../lib/helper_functions.sh
        apiEndpoints=$(oc get -n openstack PlacementAPI placement -o go-template-file=$PLACEMENT_KUTTL_DIR/../go_templates/apiEndpoints.gotemplate)
        assert_regex $apiEndpoints 'http:\/\/placement-internal\.openstack\.svc.*'
        assert_regex $apiEndpoints 'http:\/\/placement-public-openstack\.apps.*'
        ]
    logger.go:42: 17:07:34 | placement_scale/2-patch_placement_deploy | sh: 1: source: not found
    logger.go:42: 17:07:34 | placement_scale/2-patch_placement_deploy | sh: 3: assert_regex: not found
    logger.go:42: 17:07:34 | placement_scale/2-patch_placement_deploy | sh: 4: assert_regex: not found

```

What seems to be the root cause is that `sh -c source` returns `sh: 1: source: not found`.  
In my env:
```
$ which sh
/usr/bin/sh
$ ll /usr/bin/sh
lrwxrwxrwx 1 root root 4 Jan  5 14:20 /usr/bin/sh -> dash
$ 
$ sh -c source 
sh: 1: source: not found
```
I know we hit this before that the current test code depends on bash but kuttl uses sh -c to run the script. However I don't remember how I solved it locally.

2023-04-13 01:51 UTC, jamepark4 commented on kuttl-test.yaml
> +
I updated it to use . which is suppose to be more universal.  Not seeing any issues on my side when I try this, let me know if this works in yours.

2023-04-13 01:51 UTC, jamepark4 commented on kuttl-test.yaml
> +# 3. The above environment variables PLACEMENT_KUTTL_CONF and PLACEMENT_KUTTL_TEST_DIR are set
Thanks I updated the env var in the instructions to be more descriptive and forgot to update the assert yaml, it is PLACEMENT_KUTTL_TEST_DIR.

2023-04-13 07:44 UTC, gibizer requested changes
I have couple of small requests inline but overall it looks good and I was able to run the test successfully locally.

+1 for not having any install_yamls dependency within the test cases. (Having it in the preparation steps as examples how to prepare a test env is OK as it is just an example)

+1 for having a separate assert_regex function

2023-04-13 07:44 UTC, gibizer commented on kuttl-test.yaml
> +
While `.` is POSIX shell compatible (compared to `source` that is a bashism) the code that is loaded by `.`  in the test case only compatible with bash (e.g. `[[` is bashism). So if the `sh` points to other than bash then the loaded code from lib will fail on incompatibility.

I found an ugly but safe workaround for my env. I can modify the PATH for the kuttl execution to include a local directory where `sh` is soft linked to `/bin/bash`. This way I don't have to alter my local system but can still force kuttl to run /bin/bash as `sh`. So the tests are passing now for me too:
```
$ env | grep PLACEMENT
PLACEMENT_KUTTL_CONF=../placement-operator/kuttl-test.yaml
PLACEMENT_KUTTL_TEST_DIR=../placement-operator/test/kuttl/tests
$ ll /home/gibi/bin/sh-to-bash
total 0
lrwxrwxrwx 1 gibi gibi 9 Apr 13 09:02 sh -> /bin/bash
$ PATH="/home/gibi/bin/sh-to-bash:$PATH" kubectl-kuttl test --config ${PLACEMENT_KUTTL_CONF} ${PLACEMENT_KUTTL_TEST_DIR} 
[...snip...]
    harness.go:399: run tests finished
    harness.go:508: cleaning up
    harness.go:563: removing temp folder: ""
--- PASS: kuttl (66.72s)
    --- PASS: kuttl/harness (0.00s)
        --- PASS: kuttl/harness/placement_scale (56.66s)
PASS
```

2023-04-13 07:44 UTC, gibizer commented on kuttl-test.yaml
> +#    2i. make mariadb_deploy
There is a missing step. We need to deploy the placement-operator somehow as the test only creates PlacementAPI CRDs but that won't be reconciled without placement-operator running. One way to do that is `make placement` in install_yamls but other can be `OPERATOR_TEMPLATES=./templates make run` in the placement-operator repo root.

2023-04-13 07:44 UTC, gibizer commented on test/kuttl/common/errors_cleanup_placement.yaml
> +    name: placement-public
We can check that the config and script ConfigMap for placement is also deleted by the placement-operator when PlacementAPI is deleted.

These are the config maps created for PlacementAPI/placement.
```
$ oc get configmap -l placement.openstack.org/name=placement
NAME                    DATA   AGE
placement-config-data   5      2m30s
placement-scripts       2      2m30s
```

2023-04-13 07:44 UTC, gibizer commented on test/kuttl/common/assert_sample_deployment.yaml
> +---
We can also check that the config maps exists. 
```
$ oc get configmap -l placement.openstack.org/name=placement
NAME                    DATA   AGE
placement-config-data   5      2m30s
placement-scripts       2      2m30s
```

As kuttl cannot match a field partially I suggest not to try to match the Data field of the ConfigMap. Maybe later if we want to test reconfiguration then we can use assert_regex to check for parts of the placement-config-data.Data field to see if a custom configuration ended up in the given config map. But keystone actually checks the config within the service Pod in the reconfiguration test. Which also OK for me.

2023-04-13 07:44 UTC, gibizer commented on test/kuttl/common/patch_placement_deploy.yaml
> +      oc patch placementapi -n openstack placement --type='json' -p='[{"op": "replace", "path": "/spec/storageClass", "value":"local-storage"}]'
PlacementAPI.Spec  https://github.com/openstack-k8s-operators/placement-operator/blob/508390fe332e24c97625ca7d4c15088e9c09d158/api/v1beta1/placementapi_types.go#L38 does not have storageClass field. So this line should be removed.

2023-04-13 07:44 UTC, gibizer commented on test/kuttl/tests/placement_scale/05-assert.yaml
> +spec:
you can shrink the assert here to be as limited as in 04-assert.yaml

2023-04-13 07:44 UTC, gibizer commented on test/kuttl/tests/placement_scale/05-assert.yaml
> +  replicas: 0
Can we have comments in these yaml files? If so then please add a note that we are asserting spec.replicas here instead for status.availableReplicas as that field is not provided in the output if the value of it is 0.

2023-04-13 13:38 UTC, jamepark4 commented on kuttl-test.yaml
> +
Ack thanks for clarifying what was happening and I'm glad you have a solution

2023-04-13 13:39 UTC, jamepark4 commented on kuttl-test.yaml
> +#    2i. make mariadb_deploy
Ack let me try the latter approach and will update accordingly.

2023-04-13 13:40 UTC, jamepark4 commented on test/kuttl/common/errors_cleanup_placement.yaml
> +    name: placement-public
Good idea, will update to check for this as well.

2023-04-13 13:41 UTC, jamepark4 commented on test/kuttl/common/patch_placement_deploy.yaml
> +      oc patch placementapi -n openstack placement --type='json' -p='[{"op": "replace", "path": "/spec/storageClass", "value":"local-storage"}]'
Will remove, thanks.

2023-04-13 13:42 UTC, jamepark4 commented on test/kuttl/tests/placement_scale/05-assert.yaml
> +  replicas: 0
Yes that shouldn't be a problem to add.

2023-04-14 15:50 UTC, gibizer commented
/ok-to-test

2023-04-18 12:16 UTC, gibizer approved these changes
Looks good to me. Thanks!

2023-04-18 12:34 UTC, merged