add_service_db_finalizer_deletion in ReconcileDelete
openstack-k8s-operators/placement-operator pull request #50
Opened 2022-10-13 22:28 UTC by pinikomarov

Depends-On: libcommon #54 https://github.com/openstack-k8s-operators/lib-common/pull/54

2022-10-14 07:38 UTC, gibizer commented on controllers/placementapi_controller.go
> +		controllerutil.RemoveFinalizer(serviceDb, helper.GetFinalizer())
So lib-common adds the finalizer. Could you make it symmetric that lib-common does the removal too? I.e. we use the Database object for all the creation mechanism so lib-common hides how the MariaDBDatabase CR is handled. By doing "database.GetServiceDbByName" and getting back a MariaDBDatabase instance this abstraction becomes leaky. Can we move the finalizer removal also to the Database object to keep the abstraction?

2022-10-18 23:15 UTC, pinikomarov commented on controllers/placementapi_controller.go
> +		controllerutil.RemoveFinalizer(serviceDb, helper.GetFinalizer())
@gibizer @stuggi how about this approach : 
- on the lib-common's side I've added the DeleteFinalizer func to the database module: 
https://github.com/pinikomarov/lib-common/blob/add_database_finalizers/modules/database/funcs.go#L262-L263
- Then in the placementapi_controller I've put a - database.DeleteFinalizer :
https://github.com/pinikomarov/placement-operator/blob/add_service_db_finalizer_deletion/controllers/placementapi_controller.go#L211

@stuggi I know we talked about returning a *Database obj for the DeleteFinalizer,
 but as the *Database struct has the *mariadbv1.MariaDBDatabase object in it:
https://github.com/pinikomarov/lib-common/blob/add_database_finalizers/modules/database/types.go#L29
```
type Database struct {
  database         *mariadbv1.MariaDBDatabase
  databaseHostname string
  databaseName     string
```
I'm hesitant to return it so we don't "leak" any unnecessary MariaDBDatabase instance as @gibizer put it, not sure about it though ..?

2022-10-19 08:35 UTC, gibizer commented on controllers/placementapi_controller.go
> +		controllerutil.RemoveFinalizer(serviceDb, helper.GetFinalizer())
Returning a Database object that has a **private** mariadbv1.MariaDBDatabase field is totally OK as the client will not see / has no access to that private field. 

I'm not 100% what you would do with the returned Database instance in placement. If you plan to use it to call db.DeleteFinalizer() -on it, then be careful that such instance is created with NewDatabase but that is not part of  the code path of reconcileDelete(). Probably you can call NewDatabase in the reconcileDelete() code path too. So that is probably OK.

2022-10-20 11:17 UTC, pinikomarov commented on controllers/placementapi_controller.go
> +		controllerutil.RemoveFinalizer(serviceDb, helper.GetFinalizer())
@stuggi , is there a reason to return a *Database in  https://github.com/pinikomarov/lib-common/blob/add_database_finalizers/modules/database/types.go#L29
?
we can just return an error (current commit) to handle any reconcile events ..

2022-10-27 10:44 UTC, gibizer requested changes
Small and simple.

2022-11-01 00:40 UTC, pinikomarov commented on controllers/placementapi_controller.go
> +	db := database.GetDatabaseByName(ctx, helper, instance.Name)
ok

2022-11-05 05:46 UTC, pinikomarov commented
@stuggi @stuggi does this patch need a lgtm from me ? or a ok-to-test from you ?

2022-11-07 08:28 UTC, SeanMooney commented on controllers/placementapi_controller.go
> +	// remove db finalizer before the keystone one
im not really sure why this need to happen before the keystone one

2022-11-08 11:40 UTC, gibizer submitted a review, later dismissed
looks good to me

2022-11-08 11:40 UTC, gibizer commented on controllers/placementapi_controller.go
> +	// remove db finalizer before the keystone one
I don't know why we would need to do this first. I only see a single rule: We need to remove all our finalizers from other CRs first *then at last* remove the finalizer from ourselves (PlacementAPI).

2022-11-08 11:57 UTC, SeanMooney commented on controllers/placementapi_controller.go
> +	// remove db finalizer before the keystone one
ya thats what i was thinking too so i was wondering why this comment as added as it implies the ordering is important between the db and keystone which i don't think it is.

just that we remove the finaliser on other resources before ourselves as you said.

2022-11-13 22:21 UTC, pinikomarov commented on controllers/placementapi_controller.go
> +	// remove db finalizer before the keystone one
right thanks , that was a typo , it should read : 
// remove db finalizer before the placement one
I updated the comment in the file

2022-11-17 21:32 UTC, pinikomarov commented
@gibizer are we good here ? any issues ?

2022-11-18 06:50 UTC, stuggi commented
you have to update the co.mod to use the latest lib-common version with your change.

2022-11-18 10:31 UTC, gibizer commented
> @gibizer are we good here ? any issues ?

it looks good to me.

2022-11-22 13:16 UTC, pinikomarov commented
@gibizer not ready yet , I still have to update the go.mod thing - https://github.com/openstack-k8s-operators/placement-operator/pull/50#issuecomment-1319615936

2022-11-22 22:16 UTC, pinikomarov commented
@gibizer I _think_ it's ready now , add a commit with : 
`go get -u github.com/openstack-k8s-operators/lib-common/modules/database`

2022-11-23 09:31 UTC, SeanMooney commented
ignoring the fact that htis fails the checks you also have multiple commits with the same name and you create additional commits to address the feedback.

for example you have "use GetDatabaseByName" followed by "fix for GetDatabaseByName"

we do not use squash merges in this repo we try to use rebase merge where we can so every commit in the history should be independently correct.

can you do an interactive rebase and squash the fixup commit into the correct commits and make sure that the set of pathces are correct individually not just when the whole pr is merged as a unit.

in addition to that you need to address the failing tests
currently the call to delete the finalise is causing a segmentation fault

https://github.com/openstack-k8s-operators/placement-operator/actions/runs/3524854901/jobs/5921094815#step:8:24

my guess is that the finaliser has not been created in the test env so you need to update the tests to simulate that.

2022-11-23 09:34 UTC, SeanMooney requested changes
see comment https://github.com/openstack-k8s-operators/placement-operator/pull/50#issuecomment-1324770801

there are several things wrong with this patch

2022-11-24 10:12 UTC, pinikomarov commented
tnx @SeanMooney I'll start on some fixing up

2022-11-28 00:39 UTC, pinikomarov commented
@gibizer @SeanMooney  I've simplified the commits , nothing to big here so a single commit fits this pr.
Can you please give the ok to test ? 

@gibizer about the failed tests : 

https://github.com/openstack-k8s-operators/placement-operator/actions/runs/3524854901/jobs/5921094815#step:8:24
i.e `FAIL	github.com/openstack-k8s-operators/placement-operator/controllers	6.068s`
```java
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1570e00]

goroutine 832 [running]:
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile.func1()
	/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.13.1/pkg/internal/controller/controller.go:118 +0x1f4
panic({0x18252e0, 0x29d4ab0})
	/opt/hostedtoolcache/go/1.18.7/x64/src/runtime/panic.go:838 +0x207
github.com/openstack-k8s-operators/mariadb-operator/api/v1beta1.(*MariaDBDatabase).GetFinalizers(0x0?)
```
Is this a result a non existing finalizer that the test env tries to "get" ?
(because maybe since the git-workflows test env does not create it for the test like in the real env..)
So perhaps for that we should add a conditional for GetFinalizer only if it exists ..? 
like in the Keystone operator:
```go 
if !controllerutil.ContainsFinalizer(instance, helper.GetFinalizer())
```
https://github.com/pinikomarov/keystone-operator/blob/set_db_finalizer/controllers/keystoneapi_controller.go#L450-L451

Or is it something else ?

2022-11-29 11:16 UTC, gibizer requested changes

2022-11-29 11:16 UTC, gibizer commented on controllers/placementapi_controller.go
> +		return ctrl.Result{}, err
So this error handling ignores the case when MariaDBDatabase is not found,`!k8s_errors.IsNotFound(err)`. Therefore allows to db.database to be nil. This causes the panic when `db.DeleteFinalizer` is called. If MariaDBDatabase is not found it means placement controller haven't created it yet. So there is no finalizer to remove from it. You need to skip db.DeleteFinalizer call but do the rest of the finalizer removal.

```
	if !k8s_errors.IsNotFound(err) {
		if err := db.DeleteFinalizer(ctx, helper); err != nil {
			return ctrl.Result{}, err
		}
	}
```

alternatively you can change db.DeleteFinalize() in lib-common to handle the case when `db.database` is nil.

2022-11-30 00:03 UTC, pinikomarov commented on controllers/placementapi_controller.go
> +		return ctrl.Result{}, err
I think I'm ok with : 
	`if !k8s_errors.IsNotFound(err) {`  in controllers/placementapi_controller.go:216
Since error handling logic is currently on that side as it is now.		

also , if I would like to test gates locally , using openstack-k8s-operators-ci and the :ssh to repo dir and running "go test -mod=mod -v ./..." errors out with 

` msg: "failed to start the controlplane. retried 5 times: fork/exec /usr/local/kubebuilder/bin/etcd: no such file or directory",`
Is there a way set up that local gate to run ?  against a running crc cluster perhaps ?

2022-11-30 14:01 UTC, gibizer commented on controllers/placementapi_controller.go
> +		return ctrl.Result{}, err
> also , if I would like to test gates locally , using openstack-k8s-operators-ci and the :ssh to repo dir and running "go test -mod=mod -v ./..." errors out with
> 
> ` msg: "failed to start the controlplane. retried 5 times: fork/exec /usr/local/kubebuilder/bin/etcd: no such file or directory",` Is there a way set up that local gate to run ? against a running crc cluster perhaps ?

use `make test` as that make target also calls `make envtest` that does the env setup

2022-12-01 08:06 UTC, pinikomarov commented
Any more issues with this patch ?

2022-12-01 09:38 UTC, gibizer approved these changes
Looks good to me.

2022-12-01 09:38 UTC, gibizer commented
> Any more issues with this patch ? I believe the env-test should pass now :
> 
> ```shell
> [r@r placement-operator_pkomarov]$ make test
> [..]
> 
> ok      github.com/openstack-k8s-operators/placement-operator/controllers       9.465s  coverage: 43.2% of statements
> ```
> 
> can you run workflows with oktotest please ?

Could you give me some pointers to oktotest? Why we need it? How it helps?

2022-12-02 14:18 UTC, SeanMooney commented
i belive its only requried for someone that has not commit to the repo before.

so when your first patch is merged i don't think you will be asked on placement again
you will be considered a contributor at that point. also /ok-to-test i belive is only needed for prow we are still using github actions for ci at the moment.
i don't think i have currently configured it to require approval to run test for new continutors.

2022-12-02 14:28 UTC, SeanMooney approved these changes

2022-12-02 14:28 UTC, SeanMooney commented on controllers/placementapi_controller.go
> +		return ctrl.Result{}, err
this looks like it has been addressed

the new code will return if we get any error other then not found.

2022-12-02 14:28 UTC, merged